SiparisTakip.AspNetMvcUI/Models/IslemSonucModel.cs
using Newtonsoft.Json;

namespace SiparisTakip.AspNetMvcUI.Models
{
    [JsonObject(MemberSerialization.OptIn)]
    public class IslemSonucModel
    {
        [JsonProperty]
        public int IslemKodu { get; set; }
        [JsonProperty]
        public string Baslik { get; set; }
        [JsonProperty]
        public string Aciklama { get; set; }
        [JsonProperty]
        public string AciklamaDetay { get; set; }
        [JsonProperty]
        public object Data { get; set; }

        public IslemSonucModel()
        {

        }

        public IslemSonucModel(int islemKodu, string baslik, string aciklama, string aciklamaDetay, object data)
        {
            this.IslemKodu = islemKodu;
            this.Baslik = baslik;
            this.Aciklama = aciklama;
            this.AciklamaDetay = aciklamaDetay;
            this.Data = data;
        }

        public IslemSonucModel(IslemSonucuEnum.IslemSonucKodlari islemSonucKodu, string aciklama = "", string aciklamaDetay = "", object data = null)
        {
            this.IslemKodu = (int)islemSonucKodu;
            this.Baslik = islemSonucKodu.ToDescriptionString();
            this.Aciklama = aciklama;
            this.AciklamaDetay = aciklamaDetay;
            this.Data = data;
        }
    }
}

SiparisTakip.AspNetMvcUI/Models/IslemSonucuEnum.cs
using System.ComponentModel;
using static SiparisTakip.AspNetMvcUI.Models.IslemSonucuEnum;

namespace SiparisTakip.AspNetMvcUI.Models
{
    public class IslemSonucuEnum
    {
        public enum IslemSonucKodlari
        {
            [Description("BAŞARILI")]
            Basarili = 1,
            [Description("HATA")]
            Hata = 2,
            [Description("UYARI")]
            Uyari = 3,
            [Description("BİLGİLENDİRME")]
            Bilgilendirme = 4
        }

  
    }
    

    public static class ResultCodesExtensions
    {
        public static string ToDescriptionString(this IslemSonucKodlari val)
        {
            DescriptionAttribute[] attributes = (DescriptionAttribute[])val.GetType().GetField(val.ToString()).GetCustomAttributes(typeof(DescriptionAttribute), false);
            return attributes.Length > 0 ? attributes[0].Description : string.Empty;
        }
    }
}

SiparisTakip.AspNetMvcUI/Areas/Yonetim/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiparisTakip.AspNetMvcUI.Areas.Yonetim.Controllers
{
    public class LoginController : Controller
    {
        // GET: Yonetim/Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

SiparisTakip.AspNetMvcUI/Controllers/AnaSayfaController.cs
using SiparisTakip.Interfaces.Fatura;
using SiparisTakip.Interfaces.Stok;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiparisTakip.AspNetMvcUI.Controllers
{
    public class AnaSayfaController : Controller
    {
        IStokService _stokService;
        IFaturaService _faturaService;

        public AnaSayfaController(IStokService stokService,IFaturaService faturaService)
        {
            this._stokService = stokService;
            this._faturaService = faturaService;
        }


        // GET: AnaSayfa
        public ActionResult Index()
        {
            var liste = _stokService.Listele();
            return View(liste);
        }
    }
}

SiparisTakip.AspNetMvcUI/Controllers/KullaniciController.cs
using SiparisTakip.AspNetMvcUI.Models;
using SiparisTakip.Bll.KullaniciBll;
using SiparisTakip.Dal.Concrete.EntityFramework.Repository;
using SiparisTakip.Entity.Models;
using SiparisTakip.Interfaces.Kullanici;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using static SiparisTakip.AspNetMvcUI.Models.IslemSonucuEnum;

namespace SiparisTakip.AspNetMvcUI.Controllers
{
    public class KullaniciController : Controller
    {
        //IKullaniciService _kullaniciService = new KullaniciManager(new EfKullaniciRepository());

        IKullaniciService _kullaniciService;
        public KullaniciController(IKullaniciService kullaniciService)
        {
            this._kullaniciService = kullaniciService;
        }



        // GET: Kullanici
        [HttpGet]
        public ActionResult KullaniciGiris()
        {
            return View();
        }


        //[HttpPost]
        //public ActionResult KullaniciGiris(Kullanici kullanici)
        //{
        //    try
        //    {
        //        var _kullanici=_kullaniciService.KullaniciGiris(kullanici.KullaniciKodu, kullanici.Parola);
        //        if(_kullanici!=null)
        //        {
        //            Session["KullaniciId"] = _kullanici.KullaniciID;
        //            Session["KullaniciAdi"] = _kullanici.KullaniciAdi+" "+_kullanici.KullaniciSoyadi;

        //            return RedirectToAction("Index", "AnaSayfa");
        //        }
        //        else
        //        {

        //        }
        //    }
        //    catch (System.Exception error)
        //    {

        //    }
        // //return Content("Hi there!");
        //    //return RedirectToAction("Index", "AnaSayfa");

        //    return new JsonResult();
        //}

        [HttpPost]
        public JsonResult KullaniciGiris(Kullanici kullanici)
        {
            IslemSonucModel islemSonucu;
            try
            {
                var _kullanici = _kullaniciService.KullaniciGiris(kullanici.KullaniciKodu, kullanici.Parola);
                if(_kullanici!=null)
                {
                    //FormsAuthentication.SetAuthCookie("KullaniciId", false);
                    Session["KullaniciId"] = _kullanici.KullaniciID;
                    Session["KullaniciAdi"] = _kullanici.KullaniciAdi + " " + _kullanici.KullaniciSoyadi;

                    islemSonucu = new IslemSonucModel(IslemSonucKodlari.Basarili, "Kullanici Giris Basarili");
                     
                }
                else
                {
                    islemSonucu = new IslemSonucModel(IslemSonucKodlari.Uyari, "Kullanici Giris Basarisiz");
                }
            }
            catch (System.Exception error)
            {
                islemSonucu = new IslemSonucModel(IslemSonucKodlari.Hata, "Kullanıcı Giriş Kontrol Sırasında Hata Oluştu." + error.Message);
            }

            return Json(islemSonucu);
        }
        public ActionResult OturumuKapat()
        {
            //FormsAuthentication.SignOut();
            Session.Abandon();
            Session["adi"] = "dssd";
            Session.Add("soyadi", "ahmet");
            Session["adi"] = null;
            Session.Remove("adi");//belirtilen keyi iis üzerinden siler
            Session.RemoveAll();//tümünü siler
            return RedirectToAction("", "");
        }
    }
}

SiparisTakip.AspNetMvcUI/Controllers/StokController.cs
using SiparisTakip.AspNetMvcUI.Araclar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiparisTakip.AspNetMvcUI.Controllers
{
    //[Authorize]
    [YetkiKontrolu]
    public class StokController : Controller
    {
        // GET: Stok
        public ActionResult Index()
        {
            //if (Session["KullaniciId"] == null)
            //    return RedirectToAction("KullaniciGiris","Kullanici");
            return View();
        }
        //[Authorize]
        //[YetkiKontrolu("Admin)]
        [YetkiKontrolu]
        public ActionResult Kaydet()
        {
            return View();
        }
       // [Authorize]
        public ActionResult Sil()
        {
            return View();
        }
       // [Authorize]
        public ActionResult Guncelle()
        {
            return View();
        }
    }
}

SiparisTakip.AspNetMvcUI/Areas/Yonetim/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        Yönetim Giriş
    </div>
</body>
</html>

SiparisTakip.AspNetMvcUI/Views/AnaSayfa/Index.cshtml
@model IEnumerable<SiparisTakip.Entity.Models.Stok>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BarkodNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StokKodu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StokAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AlisFiyati)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AlisKdvDurumID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KdvOrani)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisFiyati)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kdv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToplamFiyati)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisKdvDurumID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aktif)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KayitZamani)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MACCAdress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notlar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResimUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HizliMenuAktif)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisFiyati2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisKdvDurumID2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisFiyati3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisKdvDurumID3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OzelKodu1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OzelKodu2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisFiyati4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisKdvDurumID4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisFiyati5)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SatisKdvDurumID5)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StokAdi2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StokKisaAciklama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StokAnahtarKelime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BarkodNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StokKodu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StokAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AlisFiyati)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AlisKdvDurumID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KdvOrani)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisFiyati)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kdv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToplamFiyati)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisKdvDurumID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Aktif)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KayitZamani)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MACCAdress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Notlar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ResimUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HizliMenuAktif)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisFiyati2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisKdvDurumID2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisFiyati3)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisKdvDurumID3)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OzelKodu1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OzelKodu2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisFiyati4)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisKdvDurumID4)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisFiyati5)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SatisKdvDurumID5)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StokAdi2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StokKisaAciklama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StokAnahtarKelime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

SiparisTakip.AspNetMvcUI/Views/Kullanici/KullaniciGiris.cshtml
@model SiparisTakip.Entity.Models.Kullanici

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Çimen Tem | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link href="~/Content/dist/css/AdminLTE.min.css" rel="stylesheet" />
    <!-- iCheck -->
    <link href="~/Content/plugins/iCheck/square/blue.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="~/Scripts/SiparisTakip.js"></script>
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="#"><b>Çimen Tem</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Giriş Yapınız</p>

            @using (Html.BeginForm("KullaniciGiris", "Kullanici", FormMethod.Post, new { @id = "FrmKullaniciGiris" }))
            {


                <div class="form-group has-feedback">

                    @Html.TextBoxFor(Model => Model.KullaniciKodu, new { @class = "form-control", @placeholder = "Kullanıcı Adı" })
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>

                <div class="form-group has-feedback">

                    @Html.PasswordFor(Model => Model.Parola, new { @class = "form-control", @placeholder = "Parola" })
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>

                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="button" onclick="KullaniciGiris();" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            }
            <div class="social-auth-links text-center">
                <p>- OR -</p>
                <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
                    <i class="fa fa-facebook"></i> Sign in using
                    Facebook
                </a>
                <a href="#" class="btn btn-block btn-social btn-google btn-flat">
                    <i class="fa fa-google-plus"></i> Sign in using
                    Google+
                </a>
            </div>
            <!-- /.social-auth-links -->
            <a href="#">I forgot my password</a><br>
            <a href="register.html" class="text-center">Register a new membership</a>
        </div>
        <!-- /.login-box-body -->
    </div>

        <div class="modal modal-danger" id="MdlBilgilendirme">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="MdlBaslik"></h4>
                    </div>
                    <div class="modal-body">
                        <p id="MdlAciklama">One fine body&hellip;</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Kapat</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
  


    <!-- /.login-box -->
    <!-- jQuery 2.2.3 -->
    <script src="~/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>

    <!-- iCheck -->
    <script src="~/Content/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });</script>
</body>
</html>

SiparisTakip.AspNetMvcUI/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
</head>
<body>
    <div> 
        @RenderBody()
    </div>
</body>
</html>

SiparisTakip.AspNetMvcUI/Views/Stok/Guncelle.cshtml
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Guncelle</h2>

SiparisTakip.AspNetMvcUI/Views/Stok/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

SiparisTakip.AspNetMvcUI/Views/Stok/Kaydet.cshtml
@{
    ViewBag.Title = "Kaydet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kaydet</h2>

SiparisTakip.AspNetMvcUI/Views/Stok/Sil.cshtml
@{
    ViewBag.Title = "Sil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sil</h2>